#Basic Vector and Matrix Operation with Numpy.


Problem - 1: Array Creation:

In [4]:
import numpy as np
#Initialize an empty array with size 2X2.
emp_array=np.empty((2,2),dtype=object)
print(emp_array)

[[None None]
 [None None]]


In [5]:
#Initialize an all one array with size 4X2.
one_array=np.ones((4,2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
#Return a new array of given shape and type, filled with fill value.
row=int(input("enter the row of array : "))
col=int(input("enter the colowm of array : "))
value=int(input("enter the value of the array : "))

array=np.full((row,col),value)
print(array)

enter the row of array : 4
enter the colowm of array : 2
enter the value of the array : 6
[[6 6]
 [6 6]
 [6 6]
 [6 6]]


In [7]:
#Return a new array of zeros with same shape and type as a given array.
given_array=np.array([[3,4,5],[1,2,6],[7,8,9]])
zero_array=np.zeros_like(given_array)
print(zero_array)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
#Return a new array of ones with same shape and type as a given array.
one_array=np.ones_like(given_array)
print(one_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.
new_list = [1,2,3,4]
new_array=np.array(new_list)
print(new_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [13]:
#Create an array with values ranging from 10 to 49.
array=np.array(range(10,49))
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [14]:
#Create a 3X3 matrix with values ranging from 0 to 8.
array=np.array(range(0,9))
matrix=array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#Create a 3X3 identity matrix.
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#Create a random array of size 30 and find the mean of the array.
array=np.array(range(30))
mean=np.mean(array)
print(mean)

14.5


In [25]:
#Create a 10X10 array with random values and find the minimum and maximum values.
array = np.random.rand(10, 10)
print (array)
min=np.min(array)
max=np.max(array)

print("minimum value in array : ",min)
print("maximum value in array : ",max)


[[0.51977697 0.69657094 0.0963346  0.79393178 0.5897801  0.81244114
  0.64800523 0.80204913 0.72544186 0.85214634]
 [0.42155421 0.18677847 0.37178514 0.98777447 0.75629699 0.76397658
  0.65036385 0.03322304 0.88150422 0.01255595]
 [0.62232797 0.67513677 0.99926403 0.63143628 0.48224945 0.53402369
  0.42304091 0.80489234 0.16580959 0.76491144]
 [0.83442402 0.87475777 0.65871856 0.06907673 0.70365653 0.75968101
  0.57832208 0.30878793 0.9330003  0.31001945]
 [0.52545899 0.7625472  0.68965681 0.95400013 0.35339495 0.24554387
  0.78121792 0.275862   0.74305442 0.13095029]
 [0.48268474 0.16777628 0.41292816 0.60473867 0.57751328 0.41146994
  0.9528757  0.04113148 0.86137987 0.15097215]
 [0.21987711 0.12361696 0.49191518 0.28559018 0.80883167 0.61203716
  0.50183045 0.28153205 0.36102507 0.62827795]
 [0.70139686 0.54153251 0.61962595 0.88335181 0.63671168 0.689632
  0.87230595 0.48207091 0.54214493 0.0776858 ]
 [0.63764326 0.84469395 0.00595811 0.03506755 0.29383718 0.6367656
  0.32641382 0.

In [26]:
# Create a zero array of size 10 and replace 5th element with 1.
array=np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
#Reverse an array arr = [1,2,0,0,4,0].
arr = [1,2,0,0,4,0]
rev_arr=arr[::-1]
print(rev_arr)

[0, 4, 0, 0, 2, 1]


In [29]:
#Create a 2d array with 1 on border and 0 inside.
array=np.ones((5,5))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.
array=np.zeros((8,8))
array[1::2,::2]=1
array[::2,1::2]=1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

In [32]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

#Add the two array.
add_array=np.add(x,y)
print("the result of adding array x and y is : ",add_array)
add_array1=np.add(v,w)
print("the result of adding array v and w is : ",add_array1)

the result of adding array x and y is :  [[ 6  8]
 [10 13]]
the result of adding array v and w is :  [20 22]


In [36]:
#Subtract the two array.
sub_array=np.subtract(x,y)
print("the result of subtracting array x and y is : ",sub_array)
sub_array1=np.subtract(v,w)
print("the result of subtracting array v and w is : ",sub_array1)

the result of subtracting array x and y is :  [[-4 -4]
 [-4 -3]]
the result of subtracting array v and w is :  [-2 -2]


In [37]:
#Multiply the array with any integers of your choice.
mul_array=np.multiply(x,y)
print("the result of multiplying array x and y is : ",mul_array)
mul_array1=np.multiply(v,w)
print("the result of multiplying array v and w is : ",mul_array1)

the result of multiplying array x and y is :  [[ 5 12]
 [21 40]]
the result of multiplying array v and w is :  [ 99 120]


In [38]:
# Find the square of each element of the array
square_array=np.square(x)
print("the result of square of each element of array x : ",square_array)
square_array1=np.square(y)
print("the result of square of each element of array y : ",square_array1)
square_array2=np.square(v)
print("the result of square of each element of array v : ",square_array2)
square_array3=np.square(w)
print("the result of square of each element of array w : ",square_array3)

the result of square of each element of array x :  [[ 1  4]
 [ 9 25]]
the result of square of each element of array y :  [[25 36]
 [49 64]]
the result of square of each element of array v :  [ 81 100]
the result of square of each element of array w :  [121 144]


In [40]:
#Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_array=np.dot(v,w)
print("the result of dot product between array v and w : ",dot_array)
dot_array1=np.dot(x,y)
print("the result of dot product between array x and y : ",dot_array1)

the result of dot product between array v and w :  219
the result of dot product between array x and y :  [[19 22]
 [50 58]]


In [46]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_array=np.concatenate((x,y),axis=1)
print("the result Concatenate x and y along colum: ",concat_array)

concat_array1=np.concatenate((v,w),axis=0)
print("the result Concatenate v and w along row: ",concat_array1)



the result Concatenate x and y along row:  [[1 2 5 6]
 [3 5 7 8]]
the result Concatenate v and w along row:  [ 9 10 11 12]


In [47]:
#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
concat_array1=np.concatenate((x,v),axis=1)
print("the result Concatenate v and w along row: ",concat_array1)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

In [50]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#Prove A.A−1 = I.
a_inv=np.linalg.inv(A)
result=np.dot(A,a_inv)
result = np.round(result, decimals=6)
print("A * A⁻¹ = \n", result)


A * A⁻¹ = 
 [[1. 0.]
 [0. 1.]]


In [53]:
#Prove AB ̸= BA.
result=np.dot(A,B)
result1=np.dot(B,A)
print("AB =",result)
print("BA =",result1)
print("AB == BA:", np.array_equal(result, result1))

AB = [[23 13]
 [51 29]]
BA = [[36 44]
 [13 16]]
AB == BA: False


In [56]:
#Prove (AB)T = BTAT
AB_transpose=np.transpose(result)
B_transpose=np.transpose(B)
A_transpose=np.transpose(A)
BTAT=np.dot(B_transpose,A_transpose)
print("(AB)T = \n",AB_transpose)
print("BTAT = \n",BTAT)
print("(AB)T = BTAT:", np.array_equal(AB_transpose, BTAT))

(AB)T = 
 [[23 51]
 [13 29]]
BTAT = 
 [[23 51]
 [13 29]]
(AB)T = BTAT: True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [60]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B=np.array([-1,-3,9])
a_inv=np.linalg.inv(A)
x=np.dot(a_inv,B)
print(x)

[ 2.  1. -2.]


#10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

Element-wise Addition:

In [64]:
#Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time

list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]
start_time = time.time()
result = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise addition:", end_time - start_time, "seconds")


Time taken for element-wise addition: 0.09197568893432617 seconds


In [65]:
#• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)
start_time = time.time()
result = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition with NumPy:", end_time - start_time, "seconds")


Time taken for element-wise addition with NumPy: 0.003559589385986328 seconds


Element-wise Multiplication

In [67]:
#Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]
start_time = time.time()
result = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise multiplication:", end_time - start_time, "seconds")

Time taken for element-wise addition: 0.09737133979797363 seconds


In [68]:
#• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)
start_time = time.time()
result = array1 * array2
end_time = time.time()
print("Time taken for element-wise addition with NumPy:", end_time - start_time, "seconds")

Time taken for element-wise addition with NumPy: 0.004141807556152344 seconds


Dot Product

In [69]:
#Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]
start_time = time.time()
result = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print("Time taken for element-wise multiplication:", end_time - start_time, "seconds")

Time taken for element-wise multiplication: 0.09217619895935059 seconds


In [70]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)
start_time = time.time()
result = np.dot(array1,array2)
end_time = time.time()
print("Time taken for element-wise addition with NumPy:", end_time - start_time, "seconds")

Time taken for element-wise addition with NumPy: 0.001836538314819336 seconds


Matrix Multiplication

In [ ]:
#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix_size = 1000
matrix_A = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix_B = [[i * j for j in range(matrix_size)] for i in range(matrix_size)]

start_time = time.time()
result = [[sum(matrix_A[i][k] * matrix_B[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()

# Print the time taken for the matrix multiplication
print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")


In [ ]:
#Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.Measure and print the time taken for this operation.
matrix_size = 1000
MatrixA = np.random.rand(matrix_size, matrix_size)
MatrixB = np.random.rand(matrix_size, matrix_size)

# Start measuring time
start_time = time.time()

# Perform matrix multiplication using NumPy's dot function
result= np.dot(MatrixA,MatrixB)

# Measure the time taken
end_time = time.time()

# Print the time taken for the matrix multiplication
print("Time taken for matrix multiplication using NumPy:", end_time - start_time, "seconds")
